version: '3'

services:
  backend:
    image: yasserbelatreche/sadaqa-backend:latest
    depends_on:
      - postgres-db
    ports:
      - "5000:80"
    env_file:
      - ../.env.backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db/sadaqa?schema=public

  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sadaqa
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
