version: "3"

services:
  frontend:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile.prod
    image: sadaqa-frontend:prod
    container_name: sadaqa-frontend-prod
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    env_file:
      - ../../.env

  backend:
    image: yasserbelatreche/sadaqa-backend:latest
    container_name: sadaqa-backend
    depends_on:
      - postgres-db
    ports:
      - "5000:80"
    env_file:
      -  ../../.env.backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db/sadaqa?schema=public

  # later on, should pull the real prod databases
  postgres-db:
    image: postgres:latest
    container_name: sadaqa-postgres-db
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sadaqa
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
