const CONNECT_ERROR = 'connect_error';
const SET_ONLINE_USERS = 'SET_ONLINE_USERS';
const NEW_CONNECTION = 'NEW_CONNECTION';
const USER_DECONNECT = 'USER_DECONNECT';
const SEND_MESSAGE = 'SEND_MESSAGE';
const NEW_MESSAGE = 'NEW_MESSAGE';
const MAKE_MESSAGES_READ = 'MAKE_MESSAGES_READ';
const IS_TYPING = 'IS_TYPING';
const STOP_TYPING = 'STOP_TYPING';
const DELETE_MESSAGE_NOTIFICATION = 'DELETE_MESSAGE_NOTIFICATION';
const CREATE_MESSAGE_NOTIFICATION = 'CREATE_MESSAGE_NOTIFICATION';
const NEW_LIKE = 'NEW_LIKE';
const NEW_LIKE_NOTIFICATION = 'NEW_LIKE_NOTIFICATION';
const NEW_POST = 'NEW_POST';
const NEW_POST_NOTIFICATION = 'NEW_POST_NOTIFICATION';

export {
  CONNECT_ERROR,
  NEW_CONNECTION,
  SET_ONLINE_USERS,
  USER_DECONNECT,
  SEND_MESSAGE,
  NEW_MESSAGE,
  MAKE_MESSAGES_READ,
  IS_TYPING,
  STOP_TYPING,
  DELETE_MESSAGE_NOTIFICATION,
  CREATE_MESSAGE_NOTIFICATION,
  NEW_LIKE,
  NEW_LIKE_NOTIFICATION,
  NEW_POST,
  NEW_POST_NOTIFICATION,
};
